trigger:
- master
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: '"yarn" | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
       yarn
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages

- script: yarn --frozen-lockfile

- script: yarn build
  displayName: 'yarn build'
  
- script: ls public
  displayName: 'ls'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'public'
    output_location: 'public'
    skip_app_build: true
    azure_static_web_apps_api_token: $(Azure_Static_Site_Token)

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'public'
    azureSubscription: $(AZURE_SUBSCRIPTION)
    Destination: 'AzureBlob'
    storage: $(STORAGE_ACCOUNT)
    ContainerName: '$web'
