trigger:
- master
  
# AzureFileCopy is only available on windows
pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: yarn
  displayName: 'install deps'

- script: yarn build
  displayName: 'yarn build'

- task: AzureStaticWebApp@0
  inputs:
    output_location: '$(System.DefaultWorkingDirectory)/public'
    skip_app_build: true
    azure_static_web_apps_api_token: $(Azure_Static_Site_Token)

- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/public'
    azureSubscription: $(AZURE_SUBSCRIPTION)
    Destination: 'AzureBlob'
    storage: $(STORAGE_ACCOUNT)
    ContainerName: '$web'